export const CREATE_QUESTION_START = 'CREATE_QUESTION_START';
export const CREATE_QUESTION_DONE = 'CREATE_QUESTION_DONE';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const ADD_ALL_QUESTIONS = 'ADD_ALL_QUESTIONS';
export const DELETE_QUESTION_START = 'DELETE_QUESTION_START';
export const DELETE_QUESTION_DONE = 'DELETE_QUESTION_DONE';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
