export const CREATE_QUESTION_START = 'CREATE_QUESTION_START';
export const CREATE_QUESTION_DONE = 'CREATE_QUESTION_DONE';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const ADD_ALL_QUESTIONS = 'ADD_ALL_QUESTIONS';
