export const FETCH_COURSES_START = 'FETCH_COURSES_START';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL';
export const DELETE_COURSE_START = 'DELETE_COURSE_START';
export const DELETE_COURSE_DONE = 'DELETE_COURSE_DONE';
