export const SET_ME = 'SET_ME';
export const ADD_OWNED_COURSE = 'ADD_OWNED_COURSE';
export const REMOVE_OWNED_COURSE = 'REMOVE_OWNED_COURSE';
export const ADD_ENROLLED_COURSE = 'ADD_ENROLLED_COURSE';
export const REMOVE_ENROLLED_COURSE = 'REMOVE_ENROLLED_COURSE';
